"use strict";

let data={
    companyName:'MasterCar',
    itemsArr:[ 
        [
            {id: 101, name:"Диск литой", price:100, type:"литой", width:6, diameter:15, model:"Alcasta15", color:"MBRS", itemGroup:"Колесные диски"},
            {id: 102, name:"Диск литой", price:115, type:"литой", width:6.5, diameter:16, model:"Alcasta16", color:"BKRS", itemGroup:"Колесные диски"},
            {id: 103, name:"Диск литой", price:140, type:"литой", width:6.5, diameter:17, model:"Alcasta17", color:"MBRS", itemGroup:"Колесные диски"},
            {id: 104, name:"Диск литой", price:155, type:"литой", width:6.5, diameter:18, model:"Alcasta18", color:"BKRS", itemGroup:"Колесные диски"},
            {id: 105, name:"Диск литой", price:165, type:"литой", width:7, diameter:19, model:"Alcasta19", color:"MBRS", itemGroup:"Колесные диски"},
            {id: 106, name:"Диск литой", price:175, type:"литой", width:7, diameter:20, model:"Alcasta20", color:"BKRS", itemGroup:"Колесные диски"},
            {id: 107, name:"Диск литой", price:185, type:"литой", width:7.5, diameter:21, model:"Alcasta21", color:"BKRS", itemGroup:"Колесные диски"},
            {id: 108, name:"Диск литой", price:200, type:"литой", width:8, diameter:22, model:"Alcasta22", color:"BKRS", itemGroup:"Колесные диски"},
            {id: 109, name:"Диск штампованный", price:80, type:"штампованный", width:6, diameter:15, model:"Trebl15", color:"черный", itemGroup:"Колесные диски"},
            {id: 110, name:"Диск штампованный", price:90, type:"штампованный", width:6.5, diameter:16, model:"Trebl16", color:"серый", itemGroup:"Колесные диски"},
            {id: 111, name:"Диск штампованный", price:100, type:"штампованный", width:6.5, diameter:17, model:"Trebl17", color:"серый", itemGroup:"Колесные диски"},
            {id: 112, name:"Диск штампованный", price:110, type:"штампованный", width:6.5, diameter:18, model:"Trebl18", color:"серый", itemGroup:"Колесные диски"},
            {id: 113, name:"Диск штампованный", price:120, type:"штампованный", width:7, diameter:19, model:"Trebl19", color:"серый", itemGroup:"Колесные диски"},
            {id: 114, name:"Диск штампованный", price:130, type:"штампованный", width:7, diameter:20, model:"Trebl20", color:"серый", itemGroup:"Колесные диски"},
            {id: 115, name:"Диск штампованный", price:140, type:"штампованный", width:7.5, diameter:21, model:"Trebl21", color:"серый", itemGroup:"Колесные диски"},
            {id: 116, name:"Диск штампованный", price:150, type:"штампованный", width:7.5, diameter:22, model:"Trebl22", color:"серый", itemGroup:"Колесные диски"},
        ],
        [
            {id:201, name:"ШИНА ЛЕТНЯЯ KAMA 175/65 R15", price:50, seson:"летняя", height:175, heightProfile:65, diameter:15, type:"легковая", model:"Breeze НК-132",itemGroup:"шины легковые"},
            {id:202, name:"ШИНА ЛЕТНЯЯ KAMA 205/55 R16", price:55, seson:"летняя", height:205, heightProfile:55, diameter:16, type:"легковая", model:"Breeze НК-132",itemGroup:"шины легковые"},
            {id:203, name:"ШИНА ЛЕТНЯЯ KAMA 195/65 R15", price:50, seson:"летняя", height:195, heightProfile:65, diameter:15, type:"легковая", model:"Breeze НК-132",itemGroup:"шины легковые"},
            {id:204, name:"ШИНА ЛЕТНЯЯ KAMA 215/65 R16", price:60, seson:"летняя", height:215, heightProfile:65, diameter:16, type:"легковая", model:"Breeze НК-132",itemGroup:"шины легковые"},
            {id:205, name:"ШИНА ЛЕТНЯЯ KAMA 215/65 R17", price:65, seson:"летняя", height:215, heightProfile:65, diameter:17, type:"легковая", model:"KAMA-365",itemGroup:"шины легковые"},
            {id:206, name:"ШИНА ЛЕТНЯЯ KAMA 220/70 R18", price:70, seson:"летняя", height:220, heightProfile:70, diameter:18, type:"легковая", model:"KAMA-365",itemGroup:"шины легковые"},
            {id:207, name:"ШИНА ЛЕТНЯЯ KAMA 220/70 R19", price:75, seson:"летняя", height:220, heightProfile:70, diameter:19, type:"легковая", model:"KAMA-365",itemGroup:"шины легковые"},
            {id:208, name:"ШИНА ЛЕТНЯЯ KAMA 220/70 R20", price:80, seson:"летняя", height:220, heightProfile:70, diameter:20, type:"легковая", model:"KAMA-365",itemGroup:"шины легковые"},
            {id:209, name:"ШИНА ЛЕТНЯЯ KAMA 225/75 R21", price:85, seson:"летняя", height:225, heightProfile:75, diameter:21, type:"легковая", model:"KAMA-365",itemGroup:"шины легковые"},
            {id:210, name:"ШИНА ЛЕТНЯЯ KAMA 225/75 R22", price:85, seson:"летняя", height:225, heightProfile:75, diameter:22, type:"легковая", model:"KAMA-365",itemGroup:"шины легковые"},
            {id:211, name:"ШИНА ЛЕТНЯЯ FORMULA ENERGY 185/65 R15", price:65, seson:"летняя", height:185, heightProfile:65, diameter:15, type:"легковая", model:"Energy",itemGroup:"шины легковые"},
            {id:212, name:"ШИНА ЛЕТНЯЯ FORMULA FORMULA ENERGY 205/55 R16", price:75, seson:"летняя", height:205, heightProfile:55, diameter:16, type:"легковая", model:"Energy",itemGroup:"шины легковые"},
            {id:213, name:"ШИНА ЛЕТНЯЯ FORMULA FORMULA ENERGY 195/65 R15", price:60, seson:"летняя", height:195, heightProfile:65, diameter:15, type:"легковая", model:"Energy",itemGroup:"шины легковые"},
            {id:214, name:"ШИНА ЛЕТНЯЯ FORMULA FORMULA ENERGY 215/65 R16", price:85, seson:"летняя", height:215, heightProfile:65, diameter:16, type:"легковая", model:"Energy",itemGroup:"шины легковые"},
            {id:215, name:"ШИНА ЛЕТНЯЯ FORMULA FORMULA ENERGY 215/65 R17", price:90, seson:"летняя", height:215, heightProfile:65, diameter:17, type:"легковая", model:"Energy",itemGroup:"шины легковые"},
            {id:216, name:"ШИНА ЛЕТНЯЯ FORMULA FORMULA ENERGY 220/70 R18", price:95, seson:"летняя", height:220, heightProfile:70, diameter:18, type:"легковая", model:"Energy",itemGroup:"шины легковые"},
            {id:217, name:"ШИНА ЛЕТНЯЯ FORMULA FORMULA ENERGY 220/70 R19", price:100, seson:"летняя", height:220, heightProfile:70, diameter:19, type:"легковая", model:"Energy",itemGroup:"шины легковые"},
            {id:218, name:"ШИНА ЛЕТНЯЯ FORMULA FORMULA ENERGY 220/70 R20", price:105, seson:"летняя", height:220, heightProfile:70, diameter:20, type:"легковая", model:"Energy",itemGroup:"шины легковые"},
            {id:219, name:"ШИНА ЛЕТНЯЯ FORMULA FORMULA ENERGY 225/75 R21", price:110, seson:"летняя", height:225, heightProfile:75, diameter:21, type:"легковая", model:"Energy",itemGroup:"шины легковые"},
            {id:220, name:"ШИНА ЛЕТНЯЯ FORMULA FORMULA ENERGY 225/75 R22", price:115, seson:"летняя", height:225, heightProfile:75, diameter:22, type:"легковая", model:"Energy",itemGroup:"шины легковые"},
            {id:221, name:"ШИНА ВСЕСЕЗОННАЯ CONTINENTAL PREMIUMCONTACT 185/65 R15", price:90, seson:"всесезонная", height:185, heightProfile:65, diameter:15, type:"легковая", model:"PremiumContact",itemGroup:"шины легковые"},
            {id:222, name:"ШИНА ВСЕСЕЗОННАЯ CONTINENTAL PREMIUMCONTACT 205/55 R16", price:95, seson:"всесезонная", height:205, heightProfile:55, diameter:16, type:"легковая", model:"PremiumContact",itemGroup:"шины легковые"},
            {id:223, name:"ШИНА ВСЕСЕЗОННАЯ CONTINENTAL PREMIUMCONTACT 195/65 R15", price:90, seson:"всесезонная", height:195, heightProfile:65, diameter:15, type:"легковая", model:"PremiumContact",itemGroup:"шины легковые"},
            {id:224, name:"ШИНА ВСЕСЕЗОННАЯ CONTINENTAL PREMIUMCONTACT 215/65 R16", price:95, seson:"всесезонная", height:215, heightProfile:65, diameter:16, type:"легковая", model:"PremiumContact",itemGroup:"шины легковые"},
            {id:225, name:"ШИНА ВСЕСЕЗОННАЯ CONTINENTAL PREMIUMCONTACT 215/65 R17", price:100, seson:"всесезонная", height:215, heightProfile:65, diameter:17, type:"легковая", model:"PremiumContact",itemGroup:"шины легковые"},
            {id:226, name:"ШИНА ВСЕСЕЗОННАЯ CONTINENTAL PREMIUMCONTACT 220/70 R18", price:105, seson:"всесезонная", height:220, heightProfile:70, diameter:18, type:"легковая", model:"PremiumContact",itemGroup:"шины легковые"},
            {id:227, name:"ШИНА ВСЕСЕЗОННАЯ CONTINENTAL PREMIUMCONTACT 220/70 R19", price:110, seson:"всесезонная", height:220, heightProfile:70, diameter:19, type:"легковая", model:"PremiumContact",itemGroup:"шины легковые"},
            {id:228, name:"ШИНА ВСЕСЕЗОННАЯ CONTINENTAL PREMIUMCONTACT 220/70 R20", price:115, seson:"всесезонная", height:220, heightProfile:70, diameter:20, type:"легковая", model:"PremiumContact",itemGroup:"шины легковые"},
            {id:229, name:"ШИНА ВСЕСЕЗОННАЯ CONTINENTAL PREMIUMCONTACT 225/75 R21", price:120, seson:"всесезонная", height:225, heightProfile:75, diameter:21, type:"легковая", model:"PremiumContact",itemGroup:"шины легковые"},
            {id:230, name:"ШИНА ВСЕСЕЗОННАЯ CONTINENTAL PREMIUMCONTACT 225/75 R22", price:125, seson:"всесезонная", height:225, heightProfile:75, diameter:22, type:"легковая", model:"PremiumContact",itemGroup:"шины легковые"},
            {id:231, name:"ШИНА ЗИМНЯЯ ШИПОВАННАЯ BRIDGESTONE ICE CRUISER 185/65 R15", price:90, seson:"зимняя шипованная", height:185, heightProfile:65, diameter:15, type:"легковая", model:"	ICE CRUISER 7000S",itemGroup:"шины легковые"},
            {id:232, name:"ШИНА ЗИМНЯЯ ШИПОВАННАЯ BRIDGESTONE ICE CRUISER 205/55 R16", price:95, seson:"зимняя шипованная", height:205, heightProfile:55, diameter:16, type:"легковая", model:"	ICE CRUISER 7000S",itemGroup:"шины легковые"},
            {id:233, name:"ШИНА ЗИМНЯЯ ШИПОВАННАЯ BRIDGESTONE ICE CRUISER 195/65 R15", price:90, seson:"зимняя шипованная", height:195, heightProfile:65, diameter:15, type:"легковая", model:"	ICE CRUISER 7000S",itemGroup:"шины легковые"},
            {id:234, name:"ШИНА ЗИМНЯЯ ШИПОВАННАЯ BRIDGESTONE ICE CRUISER 215/65 R16", price:95, seson:"зимняя шипованная", height:215, heightProfile:65, diameter:16, type:"легковая", model:"	ICE CRUISER 7000S",itemGroup:"шины легковые"},
            {id:235, name:"ШИНА ЗИМНЯЯ ШИПОВАННАЯ BRIDGESTONE ICE CRUISER 215/65 R17", price:100, seson:"зимняя шипованная", height:215, heightProfile:65, diameter:17, type:"легковая", model:"ICE CRUISER 7000S",itemGroup:"шины легковые"},
            {id:236, name:"ШИНА ЗИМНЯЯ ШИПОВАННАЯ BRIDGESTONE ICE CRUISER 220/70 R18", price:105, seson:"зимняя шипованная", height:220, heightProfile:70, diameter:18, type:"легковая", model:"ICE CRUISER 7000S",itemGroup:"шины легковые"},
            {id:237, name:"ШИНА ЗИМНЯЯ ШИПОВАННАЯ BRIDGESTONE ICE CRUISER 220/70 R19", price:110, seson:"зимняя шипованная", height:220, heightProfile:70, diameter:19, type:"легковая", model:"ICE CRUISER 7000S",itemGroup:"шины легковые"},
            {id:238, name:"ШИНА ЗИМНЯЯ ШИПОВАННАЯ BRIDGESTONE ICE CRUISER 220/70 R20", price:115, seson:"зимняя шипованная", height:220, heightProfile:70, diameter:20, type:"легковая", model:"ICE CRUISER 7000S",itemGroup:"шины легковые"},
            {id:239, name:"ШИНА ЗИМНЯЯ ШИПОВАННАЯ BRIDGESTONE ICE CRUISER 225/75 R21", price:120, seson:"зимняя шипованная", height:225, heightProfile:75, diameter:21, type:"легковая", model:"ICE CRUISER 7000S",itemGroup:"шины легковые"},
            {id:240, name:"ШИНА ЗИМНЯЯ ШИПОВАННАЯ BRIDGESTONE ICE CRUISER 225/75 R22", price:125, seson:"зимняя шипованная", height:225, heightProfile:75, diameter:22, type:"легковая", model:"ICE CRUISER 7000S",itemGroup:"шины легковые"},
            {id:241, name:"ШИНА ЛЕТНЯЯ БЕЛШИНА  175/65 R15", price:50, seson:"летняя", height:175, heightProfile:65, diameter:15, type:"легковая", model:"БЕЛШИНА 259002048",itemGroup:"шины легковые"},
            {id:242, name:"ШИНА ЛЕТНЯЯ БЕЛШИНА  205/55 R16", price:55, seson:"летняя", height:205, heightProfile:55, diameter:16, type:"легковая", model:"БЕЛШИНА 259002048",itemGroup:"шины легковые"},
            {id:243, name:"ШИНА ЛЕТНЯЯ БЕЛШИНА  195/65 R15", price:50, seson:"летняя", height:195, heightProfile:65, diameter:15, type:"легковая", model:"БЕЛШИНА 259002048",itemGroup:"шины легковые"},
            {id:244, name:"ШИНА ЛЕТНЯЯ БЕЛШИНА  215/65 R16", price:60, seson:"летняя", height:215, heightProfile:65, diameter:16, type:"легковая", model:"БЕЛШИНА 259002048",itemGroup:"шины легковые"},
            {id:245, name:"ШИНА ЛЕТНЯЯ БЕЛШИНА  215/65 R17", price:65, seson:"летняя", height:215, heightProfile:65, diameter:17, type:"легковая", model:"БЕЛШИНА 259002048",itemGroup:"шины легковые"},
            {id:246, name:"ШИНА ЛЕТНЯЯ БЕЛШИНА  220/70 R18", price:70, seson:"летняя", height:220, heightProfile:70, diameter:18, type:"легковая", model:"БЕЛШИНА 259002048",itemGroup:"шины легковые"},
            {id:247, name:"ШИНА ЛЕТНЯЯ БЕЛШИНА  220/70 R19", price:75, seson:"летняя", height:220, heightProfile:70, diameter:19, type:"легковая", model:"БЕЛШИНА 2590020485",itemGroup:"шины легковые"},
            {id:248, name:"ШИНА ЛЕТНЯЯ БЕЛШИНА  220/70 R20", price:80, seson:"летняя", height:220, heightProfile:70, diameter:20, type:"легковая", model:"БЕЛШИНА 259002048",itemGroup:"шины легковые"},
            {id:249, name:"ШИНА ЛЕТНЯЯ БЕЛШИНА  225/75 R21", price:85, seson:"летняя", height:225, heightProfile:75, diameter:21, type:"легковая", model:"БЕЛШИНА 259002048",itemGroup:"шины легковые"},
            {id:250, name:"ШИНА ЛЕТНЯЯ БЕЛШИНА  225/75 R22", price:85, seson:"летняя", height:225, heightProfile:75, diameter:22, type:"легковая", model:"БЕЛШИНА 259002048",itemGroup:"шины легковые"}, 
        ],
        [
            {id:301, name:"ЖИДКОСТЬ ТОРМОЗНАЯ ATE DOT-4 SL 0.5Л", price:35, volume:"0.5L", model:"Brake Fluid SL", itemGroup:"тормозные жидкости"},
            {id:302, name:"ЖИДКОСТЬ ТОРМОЗНАЯ ATE DOT-4 SL 1.0Л", price:60, volume:"1.0L", model:"Brake Fluid SL", itemGroup:"тормозные жидкости"},
            {id:303, name:"ЖИДКОСТЬ ТОРМОЗНАЯ BOSH DOT-4 0.5Л", price:40, volume:"0.5L", model:"Brake Fluid", itemGroup:"тормозные жидкости"},
            {id:304, name:"ЖИДКОСТЬ ТОРМОЗНАЯ BOSH DOT 4 1.0L", price:65, volume:"1.0L", model:"Brake Fluid", itemGroup:"тормозные жидкости"},
            {id:305, name:"ЖИДКОСТЬ ОХЛАЖДАЮЩАЯ FALCON TOSOL 1.0Л", price:20, volume:"1.0L", model:"FALCON TOSOL", itemGroup:"охлаждающие жидкости"},
            {id:306, name:"ЖИДКОСТЬ ОХЛАЖДАЮЩАЯ FALCON TOSOL 5.0Л", price:40, volume:"5.0L", model:"FALCON TOSOL", itemGroup:"охлаждающие жидкости"},
            {id:307, name:"ЖИДКОСТЬ ОХЛАЖДАЮЩАЯ FALCON TOSOL 10.0Л", price:55, volume:"10.0L", model:"FALCON TOSOL", itemGroup:"охлаждающие жидкости"},
            {id:308, name:"АНТИФРИЗ ЖЁЛТЫЙ EUROLINE 1.0Л", price:15, volume:"1.0L", model:"EUROLINE YELLOW ", itemGroup:"антифриз"},
            {id:309, name:"АНТИФРИЗ СИНИЙ EUROLINE 1.0Л", price:15, volume:"1.0L", model:"EUROLINE BLUE", itemGroup:"антифриз"},
            {id:310, name:"АНТИФРИЗ ЗЕЛЁНЫЙ EUROLINE 1.0Л", price:15, volume:"1.0L", model:"EUROLINE GREEN", itemGroup:"антифриз"},
            {id:311, name:"АНТИФРИЗ КРАСНЫЙ EUROLINE 1.0Л", price:15, volume:"1.0L", model:"EUROLINE RED", itemGroup:"антифриз"},
        ],
        [
            {id:401, name:"МАСЛО МОТОРНОЕ СИНТЕТИКА FORD 5 Л.", price:45, structure:"синтетика", volume:"5.0L", model:"MOTOR OIL", itemGroup:"масла ДВС"},
            {id:402, name:"МАСЛО МОТОРНОЕ СИНТЕТИКА GENERAL MOTORS 5 Л.", price:45, structure:"синтетика", volume:"5.0L", model:"MOTOR OIL", itemGroup:"масла ДВС"},
            {id:403, name:"МАСЛО МОТОРНОЕ СИНТЕТИКА HUNDAI&KIA 5 Л.", price:45, structure:"синтетика", volume:"5.0L", model:"MOTOR OIL", itemGroup:"масла ДВС"},
            {id:404, name:"МАСЛО МОТОРНОЕ СИНТЕТИКА MAZDA 5 Л.", price:45, structure:"синтетика", volume:"5.0L", model:"MOTOR OIL", itemGroup:"масла ДВС"},
            {id:405, name:"МАСЛО МОТОРНОЕ СИНТЕТИКА MERCEDES-BENZ 5 Л.", price:45, structure:"синтетика", volume:"5.0L", model:"MOTOR OIL", itemGroup:"масла ДВС"},
            {id:406, name:"МАСЛО МОТОРНОЕ СИНТЕТИКА MITSUBISHI 5 Л.", price:45, structure:"синтетика", volume:"5.0L", model:"MOTOR OIL", itemGroup:"масла ДВС"},
            {id:407, name:"МАСЛО МОТОРНОЕ СИНТЕТИКА NISSAN 5 Л.", price:45, structure:"синтетика", volume:"5.0L", model:"MOTOR OIL", itemGroup:"масла ДВС"},
            {id:408, name:"МАСЛО МОТОРНОЕ СИНТЕТИКА SHELL HELIX ULTRA 5 Л.", price:45, structure:"синтетика", volume:"5.0L", model:"MOTOR OIL", itemGroup:"масла ДВС"},
            {id:409, name:"МАСЛО МОТОРНОЕ СИНТЕТИКА TOYOTA 5 Л.", price:45, structure:"синтетика", volume:"5.0L", model:"MOTOR OIL", itemGroup:"масла ДВС"},
        ],
        
    ],
};

export default data;
